services:
  mongodb:
    image: mongo:7
    container_name: devopshub-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: devopshub-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/devopshub

  frontend:
    build: ./frontend
    container_name: devopshub-frontend
    restart: unless-stopped
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo-data:
